model = "gpt-5.6-sol"
model_reasoning_effort = "medium"
developer_instructions = "For introspection questions about Codex, inspect `~/code/github.com/openai/codex`."

[mcp_servers.chrome_devtools]
command = "bunx"
args = [ "chrome-devtools-mcp", "--channel=dev" ]

[mcp_servers.chrome_devtools.tools.click]
approval_mode = "approve"

[mcp_servers.chrome_devtools.tools.hover]
approval_mode = "approve"

[mcp_servers.chrome_devtools.tools.navigate_page]
approval_mode = "approve"

[mcp_servers.chrome_devtools.tools.new_page]
approval_mode = "approve"

[mcp_servers.chrome_devtools.tools.resize_page]
approval_mode = "approve"

[mcp_servers.chrome_devtools.tools.take_screenshot]
approval_mode = "approve"

[mcp_servers.chrome_devtools.tools.take_snapshot]
approval_mode = "approve"

[mcp_servers.codebase]
url = "https://code.byted.org/api/mcp/codebase/mcp"

  [mcp_servers.codebase.env_http_headers]
  X-Code-User-JWT = "BYTED_AI_JWT"

[mcp_servers.lark]
url = "https://code.byted.org/api/mcp/lark/mcp"

  [mcp_servers.lark.env_http_headers]
  X-Code-User-JWT = "BYTED_AI_JWT"

[mcp_servers.bytedance]
url = "https://0r2y3xvu.mcp.bytedance.net/mcp"

  [mcp_servers.bytedance.env_http_headers]
  X-Code-User-JWT = "BYTED_AI_JWT"

[mcp_servers.fff]
command = "fff-mcp"

[mcp_servers.fff.tools.find_files]
approval_mode = "approve"

[mcp_servers.fff.tools.multi_grep]
approval_mode = "approve"

[mcp_servers.fff.tools.grep]
approval_mode = "approve"

[features]
hooks = true
codex_hooks = true
js_repl = true

[tui]
terminal_resize_reflow_max_rows = 0

  [tui.model_availability_nux]
  "gpt-5.5" = 4
  "gpt-5.6-sol" = 3

[projects."/Users/bytedance/workspace/github.com/openai/codex"]
trust_level = "trusted"

[projects."/Users/bytedance/workspace/github.com/vegerot/dotfiles"]
trust_level = "trusted"

[projects."/Users/bytedance/code/github.com/openai/codex"]
trust_level = "trusted"

[projects."/Users/bytedance/code/github.com/google-gemini/gemini-cli"]
trust_level = "trusted"

[projects."/Users/bytedance/code/github.com/neovim/neovim"]
trust_level = "trusted"

[projects."/Users/bytedance/.local/share/nvim/site/pack/core/opt"]
trust_level = "trusted"

[projects."/Users/bytedance/code/github.com/vegerot/dotfiles"]
trust_level = "trusted"


[hooks.state."/Users/bytedance/.codex/hooks.json:user_prompt_submit:0:0"]
trusted_hash = "sha256:4365d26eab04ab86afb3a21b30dfa267a333f9dfd1d3c1e88c1dcfc1af0dea2c"
