source $VIMRUNTIME/defaults.vim
set tabstop=4
set clipboard=unnamed
set ignorecase

"" grep start
" use ripgrep instead of grep
set grepprg=rg\ --vimgrep\ --no-heading

command -nargs=+ Gr :grep <args>
"" grep end


nmap <C-j> <C-w>j
nmap <C-k> <C-w>k
nmap <C-h> <C-w>h
nmap <C-l> <C-w>l

command Edir :e %:h
command VEdir :Ve %:h

set path+=./**/*
set path+=,./**/*
